In [11]:
from world.envs import OnePlayerEnv, TwoPlayerEnv
from world.realm import Realm
from world.map_loaders.single_team import SingleTeamLabyrinthMapLoader
from world.map_loaders.two_teams import TwoTeamLabyrinthMapLoader

In [12]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [45]:
env = OnePlayerEnv(Realm(SingleTeamLabyrinthMapLoader(), 1))

In [46]:
state, info = env.reset()

In [20]:
type(state)

numpy.ndarray

In [23]:
print(state[..., 0])

[[-1 -1 -1 ... -1 -1 -1]
 [-1  2  2 ...  2 -1 -1]
 [-1 -1 -1 ... -1 -1 -1]
 ...
 [-1 -1  2 ... -1 -1 -1]
 [ 2 -1 -1 ... -1  2  2]
 [-1 -1 -1 ... -1 -1 -1]]


In [18]:
[(item["x"], item["y"]) for item in info["predators"]]

{'eaten': {},
 'preys': [{'x': 0,
   'y': 22,
   'id': 0,
   'team': 2,
   'alive': True,
   'bonus_count': 0},
  {'x': 0, 'y': 38, 'id': 1, 'team': 2, 'alive': True, 'bonus_count': 0},
  {'x': 1, 'y': 1, 'id': 2, 'team': 2, 'alive': True, 'bonus_count': 0},
  {'x': 1, 'y': 4, 'id': 3, 'team': 2, 'alive': True, 'bonus_count': 0},
  {'x': 1, 'y': 5, 'id': 4, 'team': 2, 'alive': True, 'bonus_count': 0},
  {'x': 1, 'y': 27, 'id': 5, 'team': 2, 'alive': True, 'bonus_count': 0},
  {'x': 1, 'y': 33, 'id': 6, 'team': 2, 'alive': True, 'bonus_count': 0},
  {'x': 2, 'y': 1, 'id': 7, 'team': 2, 'alive': True, 'bonus_count': 0},
  {'x': 2, 'y': 13, 'id': 8, 'team': 2, 'alive': True, 'bonus_count': 0},
  {'x': 2, 'y': 28, 'id': 9, 'team': 2, 'alive': True, 'bonus_count': 0},
  {'x': 2, 'y': 29, 'id': 10, 'team': 2, 'alive': True, 'bonus_count': 0},
  {'x': 2, 'y': 34, 'id': 11, 'team': 2, 'alive': True, 'bonus_count': 0},
  {'x': 2, 'y': 37, 'id': 12, 'team': 2, 'alive': True, 'bonus_count': 0},
 

In [24]:
from world.scripted_agents import ClosestTargetAgent

In [47]:
agent = ClosestTargetAgent()


In [48]:
from world.utils import RenderedEnvWrapper

In [49]:
wrap = RenderedEnvWrapper(env)

In [50]:
state, info = wrap.reset()
agent.reset(state, 0)

In [52]:
done = False
while not done:
    state, done, info = wrap.step(agent.get_actions(state, 0))
    print('a')

a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a


In [53]:
wrap.render()

In [54]:
info

{'eaten': {(1, 24): (0, 0)},
 'preys': [{'x': 2,
   'y': 0,
   'id': 0,
   'team': 1,
   'alive': False,
   'bonus_count': 0},
  {'x': 0, 'y': 5, 'id': 1, 'team': 1, 'alive': False, 'bonus_count': 0},
  {'x': 6, 'y': 18, 'id': 2, 'team': 1, 'alive': False, 'bonus_count': 0},
  {'x': 10, 'y': 26, 'id': 3, 'team': 1, 'alive': False, 'bonus_count': 0},
  {'x': 1, 'y': 1, 'id': 4, 'team': 1, 'alive': False, 'bonus_count': 0},
  {'x': 5, 'y': 30, 'id': 5, 'team': 1, 'alive': False, 'bonus_count': 0},
  {'x': 6, 'y': 30, 'id': 6, 'team': 1, 'alive': False, 'bonus_count': 0},
  {'x': 1, 'y': 0, 'id': 7, 'team': 1, 'alive': False, 'bonus_count': 0},
  {'x': 11, 'y': 10, 'id': 8, 'team': 1, 'alive': False, 'bonus_count': 0},
  {'x': 10, 'y': 6, 'id': 9, 'team': 1, 'alive': False, 'bonus_count': 0},
  {'x': 1, 'y': 13, 'id': 10, 'team': 1, 'alive': False, 'bonus_count': 0},
  {'x': 1, 'y': 37, 'id': 11, 'team': 1, 'alive': False, 'bonus_count': 0},
  {'x': 9, 'y': 14, 'id': 12, 'team': 1, 'alive